services:
  - type: web
    name: build-performance-demo-web
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: build-performance-demo-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: build-performance-demo-cache
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: build-performance-demo-web-node
    runtime: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: build-performance-demo-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: build-performance-demo-cache
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
    autoDeploy: true

  - type: redis
    name: build-performance-demo-cache
    ipAllowList: []
    plan: standard
    maxmemoryPolicy: noeviction

databases:
  - name: build-performance-demo-db
    databaseName: app_db
    user: app_user
    plan: basic-1gb
    ipAllowList: []