name: Docker Build for Render.com

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=docker,dest=/tmp/app-image.tar
    
    - name: Test Docker image
      run: |
        docker load --input /tmp/app-image.tar
        docker image ls
        echo "Docker image built successfully"
    
    - name: Push to GitHub Container Registry
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Get repo name in lowercase
      id: repo-name
      run: |
        REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        echo "repo_lower=$REPO_LOWER" >> $GITHUB_OUTPUT
      
    - name: Deploy to Registry
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ steps.repo-name.outputs.repo_lower }}:latest
          ghcr.io/${{ steps.repo-name.outputs.repo_lower }}:${{ github.sha }}
        cache-from: type=gha 